# version: "3.8"
services:
  backend:
    image: coderbillzay/jio-health
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - jiohealth
    links:
      - db
    volumes:
      - ../assets:/app/assets
  
  db:
    image: postgres
    container_name: postgres
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jiohealth
    volumes:
      - ../deploy/postgresql:/var/lib/postgresql/data
      # seeding scripts
      - ../deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jiohealth

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    # restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ../deploy/pgadmin:/var/lib/pgadmin
    networks:
      - jiohealth

  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: test
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #   volumes:
  #     # seeding scripts
  #     - ../deploy/mongodb/mongo-entrypoint:/docker-entrypoint-initdb.d
  #     # named volumes
  #     - ../deploy/mongodb/db:/data/db
  #     - ../deploy/mongodb/mongoconfig:/data/configdb
  #   networks:
  #     - jiohealth

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  jiohealth:
    driver: bridge