definitions:
  handlers.ForgotPass:
    properties:
      confirmPassword:
        type: string
      newPassword:
        type: string
    type: object
  handlers.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.ResponseDataType:
    properties:
      data: {}
      message:
        type: string
      statusCode:
        type: integer
    type: object
  types.ResponseLogin:
    properties:
      token:
        type: string
      userId:
        type: integer
    type: object
  types.Users:
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      roleId:
        type: integer
      userId:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/change-password:
    post:
      consumes:
      - application/json
      description: Returns Change Password Successful
      parameters:
      - description: Login
        in: body
        name: userLogin
        required: true
        schema:
          $ref: '#/definitions/handlers.ForgotPass'
      - description: userId
        in: query
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ResponseDataType'
      summary: Change Password
      tags:
      - Users
  /api/v1/forgot-password:
    get:
      consumes:
      - application/json
      description: Returns Sent to Your Email Successful
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ResponseDataType'
      summary: Forgot Password
      tags:
      - Users
  /api/v1/get-user:
    get:
      consumes:
      - application/json
      description: Returns user details by Id
      parameters:
      - description: User Id
        in: query
        name: userId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Users'
      security:
      - Bearer: []
      summary: Get user details by Id
      tags:
      - Users
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Returns Login Successful
      parameters:
      - description: Login
        in: body
        name: userLogin
        required: true
        schema:
          $ref: '#/definitions/handlers.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ResponseLogin'
      summary: Login
      tags:
      - Users
  /api/v1/sign-up:
    post:
      consumes:
      - application/json
      description: Returns  Sign Up Successful
      parameters:
      - description: New User
        in: body
        name: userId
        required: true
        schema:
          $ref: '#/definitions/types.Users'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ResponseDataType'
      summary: Sign Up Account
      tags:
      - Users
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
